import { Sector, Job } from '@/types/career';

export const sectors: Sector[] = [
  {
    id: 'software-it',
    name: 'Software & IT',
    icon: '💻',
    description: 'Build the digital world',
    gradient: { from: '#FF0050', to: '#FF6B9D' },
  },
  {
    id: 'cloud-computing',
    name: 'Cloud Computing',
    icon: '☁️',
    description: 'Power of distributed systems',
    gradient: { from: '#00C9FF', to: '#92FE9D' },
  },
  {
    id: 'cybersecurity',
    name: 'Cybersecurity',
    icon: '🔐',
    description: 'Protect the digital realm',
    gradient: { from: '#F857A6', to: '#FF5858' },
  },
  {
    id: 'mechanical',
    name: 'Mechanical Engineering',
    icon: '⚙️',
    description: 'Design and build machines',
    gradient: { from: '#FDBB2D', to: '#22C1C3' },
  },
  {
    id: 'electronics',
    name: 'Electronics',
    icon: '🔌',
    description: 'Power of circuits and chips',
    gradient: { from: '#667EEA', to: '#764BA2' },
  },
  {
    id: 'civil',
    name: 'Civil Engineering',
    icon: '🏗️',
    description: 'Build infrastructure',
    gradient: { from: '#F093FB', to: '#F5576C' },
  },
  {
    id: 'medical',
    name: 'Medical',
    icon: '⚕️',
    description: 'Healing and healthcare',
    gradient: { from: '#4FACFE', to: '#00F2FE' },
  },
  {
    id: 'design-ux',
    name: 'Design & UX',
    icon: '🎨',
    description: 'Craft beautiful experiences',
    gradient: { from: '#FA709A', to: '#FEE140' },
  },
  {
    id: 'management',
    name: 'Management',
    icon: '📊',
    description: 'Lead and strategize',
    gradient: { from: '#30CFD0', to: '#330867' },
  },
  {
    id: 'finance',
    name: 'Finance',
    icon: '💰',
    description: 'Money and markets',
    gradient: { from: '#A8EDEA', to: '#FED6E3' },
  },
];

export const jobs: Job[] = [
  // Software & IT (5 jobs)
  {
    id: 'full-stack-developer',
    name: 'Full Stack Developer',
    icon: '🌐',
    sectorId: 'software-it',
    description: 'Build complete web applications',
    detailedDescription: 'Full Stack Developers create both frontend and backend of web applications. They work with databases, servers, APIs, and user interfaces to deliver complete digital solutions.',
    salary: { min: 60000, max: 150000, currency: 'USD' },
    skills: ['JavaScript', 'React', 'Node.js', 'SQL', 'Git', 'REST APIs'],
    difficulty: 'intermediate',
    roadmap: [
      { step: 1, title: 'HTML/CSS Basics', description: 'Learn web fundamentals' },
      { step: 2, title: 'JavaScript', description: 'Master programming basics' },
      { step: 3, title: 'Frontend Framework', description: 'Learn React or Vue' },
      { step: 4, title: 'Backend Development', description: 'Node.js and databases' },
      { step: 5, title: 'DevOps Basics', description: 'Deployment and CI/CD' },
    ],
    certificates: [
      { name: 'AWS Certified Developer', type: 'optional' },
      { name: 'MongoDB Certified Developer', type: 'optional' },
    ],
    links: [
      { name: 'FreeCodeCamp Full Stack', url: 'https://freecodecamp.org', platform: 'Other', type: 'free' },
      { name: 'Complete Web Dev Bootcamp', url: 'https://udemy.com', platform: 'Udemy', type: 'paid' },
    ],
  },
  {
    id: 'mobile-developer',
    name: 'Mobile App Developer',
    icon: '📱',
    sectorId: 'software-it',
    description: 'Create apps for smartphones',
    detailedDescription: 'Mobile App Developers build applications for iOS and Android platforms. They work with native or cross-platform frameworks to create engaging mobile experiences.',
    salary: { min: 65000, max: 140000, currency: 'USD' },
    skills: ['React Native', 'Flutter', 'Swift', 'Kotlin', 'Mobile UI/UX', 'APIs'],
    difficulty: 'intermediate',
    roadmap: [
      { step: 1, title: 'Programming Basics', description: 'Learn JavaScript or Dart' },
      { step: 2, title: 'Mobile Framework', description: 'Choose React Native or Flutter' },
      { step: 3, title: 'UI/UX Design', description: 'Learn mobile design patterns' },
      { step: 4, title: 'App Store Publishing', description: 'Deploy to stores' },
    ],
    certificates: [
      { name: 'Google Associate Android Developer', type: 'optional' },
      { name: 'Meta React Native Certificate', type: 'optional' },
    ],
    links: [
      { name: 'React Native Tutorial', url: 'https://youtube.com', platform: 'YouTube', type: 'free' },
      { name: 'Flutter & Dart Bootcamp', url: 'https://udemy.com', platform: 'Udemy', type: 'paid' },
    ],
  },
  {
    id: 'data-scientist',
    name: 'Data Scientist',
    icon: '📊',
    sectorId: 'software-it',
    description: 'Extract insights from data',
    detailedDescription: 'Data Scientists analyze complex datasets to extract meaningful insights. They use statistical methods, machine learning, and programming to solve business problems.',
    salary: { min: 80000, max: 180000, currency: 'USD' },
    skills: ['Python', 'Machine Learning', 'Statistics', 'SQL', 'Pandas', 'Visualization'],
    difficulty: 'advanced',
    roadmap: [
      { step: 1, title: 'Python Programming', description: 'Learn Python basics' },
      { step: 2, title: 'Statistics & Math', description: 'Probability and statistics' },
      { step: 3, title: 'Data Analysis', description: 'Pandas and NumPy' },
      { step: 4, title: 'Machine Learning', description: 'ML algorithms and models' },
      { step: 5, title: 'Deep Learning', description: 'Neural networks' },
    ],
    certificates: [
      { name: 'Google Data Analytics Certificate', type: 'required' },
      { name: 'IBM Data Science Professional', type: 'optional' },
    ],
    links: [
      { name: 'Data Science Playlist', url: 'https://youtube.com', platform: 'YouTube', type: 'free' },
      { name: 'Data Science Masterclass', url: 'https://coursera.org', platform: 'Coursera', type: 'paid' },
    ],
  },
  {
    id: 'devops-engineer',
    name: 'DevOps Engineer',
    icon: '🔄',
    sectorId: 'software-it',
    description: 'Automate and optimize workflows',
    detailedDescription: 'DevOps Engineers bridge development and operations teams. They automate deployment pipelines, manage infrastructure, and ensure smooth continuous delivery.',
    salary: { min: 75000, max: 160000, currency: 'USD' },
    skills: ['Docker', 'Kubernetes', 'CI/CD', 'AWS', 'Linux', 'Automation'],
    difficulty: 'advanced',
    roadmap: [
      { step: 1, title: 'Linux Fundamentals', description: 'Master command line' },
      { step: 2, title: 'Cloud Platforms', description: 'AWS, Azure, or GCP' },
      { step: 3, title: 'Containers', description: 'Docker and Kubernetes' },
      { step: 4, title: 'CI/CD Tools', description: 'Jenkins, GitLab CI' },
    ],
    certificates: [
      { name: 'AWS Certified DevOps Engineer', type: 'required' },
      { name: 'Certified Kubernetes Administrator', type: 'optional' },
    ],
    links: [
      { name: 'DevOps Tutorial', url: 'https://youtube.com', platform: 'YouTube', type: 'free' },
      { name: 'DevOps Complete Course', url: 'https://udemy.com', platform: 'Udemy', type: 'paid' },
    ],
  },
  {
    id: 'ai-ml-engineer',
    name: 'AI/ML Engineer',
    icon: '🤖',
    sectorId: 'software-it',
    description: 'Build intelligent systems',
    detailedDescription: 'AI/ML Engineers develop artificial intelligence and machine learning models. They work on computer vision, NLP, and predictive analytics to create smart applications.',
    salary: { min: 90000, max: 200000, currency: 'USD' },
    skills: ['Python', 'TensorFlow', 'PyTorch', 'Deep Learning', 'NLP', 'Computer Vision'],
    difficulty: 'advanced',
    roadmap: [
      { step: 1, title: 'Python & Math', description: 'Linear algebra and calculus' },
      { step: 2, title: 'Machine Learning', description: 'Classical ML algorithms' },
      { step: 3, title: 'Deep Learning', description: 'Neural networks fundamentals' },
      { step: 4, title: 'Specialized AI', description: 'NLP or Computer Vision' },
      { step: 5, title: 'MLOps', description: 'Deploy ML models' },
    ],
    certificates: [
      { name: 'TensorFlow Developer Certificate', type: 'required' },
      { name: 'Deep Learning Specialization', type: 'optional' },
    ],
    links: [
      { name: 'AI ML Free Course', url: 'https://youtube.com', platform: 'YouTube', type: 'free' },
      { name: 'Machine Learning A-Z', url: 'https://udemy.com', platform: 'Udemy', type: 'paid' },
    ],
  },

  // Cloud Computing (5 jobs)
  {
    id: 'cloud-architect',
    name: 'Cloud Architect',
    icon: '🏛️',
    sectorId: 'cloud-computing',
    description: 'Design cloud infrastructure',
    detailedDescription: 'Cloud Architects design and oversee cloud computing strategies. They plan scalable, secure, and cost-effective cloud solutions for organizations.',
    salary: { min: 100000, max: 190000, currency: 'USD' },
    skills: ['AWS', 'Azure', 'GCP', 'Networking', 'Security', 'Architecture Design'],
    difficulty: 'advanced',
    roadmap: [
      { step: 1, title: 'Cloud Fundamentals', description: 'Understand cloud basics' },
      { step: 2, title: 'Choose Platform', description: 'Master AWS, Azure, or GCP' },
      { step: 3, title: 'Architecture Patterns', description: 'Learn design patterns' },
      { step: 4, title: 'Security & Compliance', description: 'Cloud security best practices' },
    ],
    certificates: [
      { name: 'AWS Solutions Architect Professional', type: 'required' },
      { name: 'Azure Solutions Architect', type: 'optional' },
    ],
    links: [
      { name: 'Cloud Architecture Basics', url: 'https://youtube.com', platform: 'YouTube', type: 'free' },
      { name: 'AWS Solutions Architect', url: 'https://udemy.com', platform: 'Udemy', type: 'paid' },
    ],
  },
  {
    id: 'cloud-security-specialist',
    name: 'Cloud Security Specialist',
    icon: '🛡️',
    sectorId: 'cloud-computing',
    description: 'Secure cloud environments',
    detailedDescription: 'Cloud Security Specialists protect cloud infrastructure from threats. They implement security policies, monitor for vulnerabilities, and ensure compliance.',
    salary: { min: 85000, max: 170000, currency: 'USD' },
    skills: ['Cloud Security', 'IAM', 'Encryption', 'Compliance', 'Threat Detection'],
    difficulty: 'advanced',
    roadmap: [
      { step: 1, title: 'Cloud Basics', description: 'Learn cloud fundamentals' },
      { step: 2, title: 'Security Fundamentals', description: 'Cybersecurity basics' },
      { step: 3, title: 'Cloud Security Tools', description: 'AWS Security, Azure Security' },
      { step: 4, title: 'Compliance', description: 'GDPR, HIPAA, SOC2' },
    ],
    certificates: [
      { name: 'AWS Certified Security Specialty', type: 'required' },
      { name: 'CCSP (Certified Cloud Security Professional)', type: 'optional' },
    ],
    links: [
      { name: 'Cloud Security Fundamentals', url: 'https://youtube.com', platform: 'YouTube', type: 'free' },
      { name: 'Cloud Security Course', url: 'https://coursera.org', platform: 'Coursera', type: 'paid' },
    ],
  },
  {
    id: 'site-reliability-engineer',
    name: 'Site Reliability Engineer',
    icon: '⚡',
    sectorId: 'cloud-computing',
    description: 'Ensure system reliability',
    detailedDescription: 'SREs maintain and improve system reliability and performance. They combine software engineering with operations to build scalable and reliable systems.',
    salary: { min: 95000, max: 185000, currency: 'USD' },
    skills: ['Monitoring', 'Incident Response', 'Automation', 'Performance Tuning', 'Scripting'],
    difficulty: 'advanced',
    roadmap: [
      { step: 1, title: 'System Administration', description: 'Linux and networking' },
      { step: 2, title: 'Programming', description: 'Python or Go' },
      { step: 3, title: 'Monitoring Tools', description: 'Prometheus, Grafana' },
      { step: 4, title: 'Incident Management', description: 'On-call practices' },
    ],
    certificates: [
      { name: 'Google Cloud SRE Certification', type: 'optional' },
      { name: 'Certified Kubernetes Administrator', type: 'optional' },
    ],
    links: [
      { name: 'SRE Fundamentals', url: 'https://youtube.com', platform: 'YouTube', type: 'free' },
      { name: 'SRE Course', url: 'https://udemy.com', platform: 'Udemy', type: 'paid' },
    ],
  },
  {
    id: 'serverless-developer',
    name: 'Serverless Developer',
    icon: '⚙️',
    sectorId: 'cloud-computing',
    description: 'Build without managing servers',
    detailedDescription: 'Serverless Developers create applications using cloud functions and managed services. They focus on code without worrying about infrastructure.',
    salary: { min: 70000, max: 150000, currency: 'USD' },
    skills: ['AWS Lambda', 'Azure Functions', 'Event-Driven', 'APIs', 'NoSQL'],
    difficulty: 'intermediate',
    roadmap: [
      { step: 1, title: 'Cloud Basics', description: 'Learn cloud services' },
      { step: 2, title: 'Functions', description: 'AWS Lambda or Azure Functions' },
      { step: 3, title: 'Event Architecture', description: 'Event-driven patterns' },
      { step: 4, title: 'Serverless Framework', description: 'Deployment tools' },
    ],
    certificates: [
      { name: 'AWS Certified Developer', type: 'optional' },
    ],
    links: [
      { name: 'Serverless Intro', url: 'https://youtube.com', platform: 'YouTube', type: 'free' },
      { name: 'Serverless Complete Guide', url: 'https://udemy.com', platform: 'Udemy', type: 'paid' },
    ],
  },
  {
    id: 'cloud-cost-analyst',
    name: 'Cloud Cost Analyst',
    icon: '💵',
    sectorId: 'cloud-computing',
    description: 'Optimize cloud spending',
    detailedDescription: 'Cloud Cost Analysts monitor and optimize cloud expenses. They identify cost-saving opportunities and implement financial governance.',
    salary: { min: 60000, max: 120000, currency: 'USD' },
    skills: ['Cost Management', 'Cloud Billing', 'Analytics', 'Budgeting', 'Optimization'],
    difficulty: 'beginner',
    roadmap: [
      { step: 1, title: 'Cloud Fundamentals', description: 'Learn cloud services' },
      { step: 2, title: 'Billing & Pricing', description: 'Understand cloud pricing' },
      { step: 3, title: 'Cost Tools', description: 'AWS Cost Explorer, Azure Cost' },
      { step: 4, title: 'Optimization', description: 'Cost-saving strategies' },
    ],
    certificates: [
      { name: 'AWS Cloud Financial Management', type: 'optional' },
    ],
    links: [
      { name: 'Cloud Cost Management', url: 'https://youtube.com', platform: 'YouTube', type: 'free' },
      { name: 'Cloud FinOps Course', url: 'https://udemy.com', platform: 'Udemy', type: 'paid' },
    ],
  },

  // Cybersecurity (5 jobs)
  {
    id: 'ethical-hacker',
    name: 'Ethical Hacker',
    icon: '🕵️',
    sectorId: 'cybersecurity',
    description: 'Test security by hacking',
    detailedDescription: 'Ethical Hackers identify vulnerabilities in systems by simulating attacks. They help organizations strengthen their security before malicious hackers strike.',
    salary: { min: 75000, max: 165000, currency: 'USD' },
    skills: ['Penetration Testing', 'Network Security', 'Vulnerability Assessment', 'Exploitation'],
    difficulty: 'advanced',
    roadmap: [
      { step: 1, title: 'Networking Basics', description: 'TCP/IP, protocols' },
      { step: 2, title: 'Linux & Commands', description: 'Master Linux environment' },
      { step: 3, title: 'Security Tools', description: 'Kali Linux, Metasploit' },
      { step: 4, title: 'Web Security', description: 'OWASP Top 10' },
      { step: 5, title: 'Certification', description: 'CEH or OSCP' },
    ],
    certificates: [
      { name: 'Certified Ethical Hacker (CEH)', type: 'required' },
      { name: 'Offensive Security Certified Professional (OSCP)', type: 'optional' },
    ],
    links: [
      { name: 'Ethical Hacking Free Course', url: 'https://youtube.com', platform: 'YouTube', type: 'free' },
      { name: 'Complete Ethical Hacking', url: 'https://udemy.com', platform: 'Udemy', type: 'paid' },
    ],
  },
  {
    id: 'security-analyst',
    name: 'Security Analyst',
    icon: '🔍',
    sectorId: 'cybersecurity',
    description: 'Monitor and respond to threats',
    detailedDescription: 'Security Analysts monitor networks for security breaches and investigate violations. They implement security measures and respond to incidents.',
    salary: { min: 65000, max: 140000, currency: 'USD' },
    skills: ['SIEM', 'Threat Detection', 'Incident Response', 'Security Protocols', 'Log Analysis'],
    difficulty: 'intermediate',
    roadmap: [
      { step: 1, title: 'IT Fundamentals', description: 'Networks and systems' },
      { step: 2, title: 'Security Basics', description: 'Security+ knowledge' },
      { step: 3, title: 'SIEM Tools', description: 'Splunk, ELK Stack' },
      { step: 4, title: 'Incident Response', description: 'Handle security incidents' },
    ],
    certificates: [
      { name: 'CompTIA Security+', type: 'required' },
      { name: 'GIAC Security Essentials (GSEC)', type: 'optional' },
    ],
    links: [
      { name: 'Security Analyst Training', url: 'https://youtube.com', platform: 'YouTube', type: 'free' },
      { name: 'Cybersecurity Analyst', url: 'https://coursera.org', platform: 'Coursera', type: 'paid' },
    ],
  },
  {
    id: 'cryptographer',
    name: 'Cryptographer',
    icon: '🔐',
    sectorId: 'cybersecurity',
    description: 'Design secure encryption',
    detailedDescription: 'Cryptographers develop encryption methods to protect sensitive information. They design algorithms and protocols for secure communication.',
    salary: { min: 80000, max: 170000, currency: 'USD' },
    skills: ['Cryptography', 'Mathematics', 'Algorithms', 'Security Protocols', 'Programming'],
    difficulty: 'advanced',
    roadmap: [
      { step: 1, title: 'Mathematics', description: 'Number theory, algebra' },
      { step: 2, title: 'Programming', description: 'Python, C++' },
      { step: 3, title: 'Cryptography Basics', description: 'Encryption algorithms' },
      { step: 4, title: 'Advanced Crypto', description: 'Public key cryptography' },
      { step: 5, title: 'Blockchain', description: 'Optional: blockchain tech' },
    ],
    certificates: [
      { name: 'Certified Information Systems Security Professional (CISSP)', type: 'optional' },
    ],
    links: [
      { name: 'Cryptography Basics', url: 'https://youtube.com', platform: 'YouTube', type: 'free' },
      { name: 'Applied Cryptography', url: 'https://coursera.org', platform: 'Coursera', type: 'paid' },
    ],
  },
  {
    id: 'forensics-analyst',
    name: 'Digital Forensics Analyst',
    icon: '🔬',
    sectorId: 'cybersecurity',
    description: 'Investigate cyber crimes',
    detailedDescription: 'Digital Forensics Analysts investigate cyber crimes by collecting and analyzing digital evidence. They help law enforcement and organizations solve security incidents.',
    salary: { min: 70000, max: 145000, currency: 'USD' },
    skills: ['Forensic Tools', 'Evidence Collection', 'Data Recovery', 'Legal Procedures', 'Analysis'],
    difficulty: 'advanced',
    roadmap: [
      { step: 1, title: 'IT Basics', description: 'Systems and networks' },
      { step: 2, title: 'Forensic Tools', description: 'EnCase, FTK' },
      { step: 3, title: 'Legal Knowledge', description: 'Cyber law basics' },
      { step: 4, title: 'Investigation', description: 'Evidence handling' },
    ],
    certificates: [
      { name: 'GIAC Certified Forensic Analyst (GCFA)', type: 'required' },
      { name: 'Certified Computer Forensics Examiner (CCFE)', type: 'optional' },
    ],
    links: [
      { name: 'Digital Forensics Intro', url: 'https://youtube.com', platform: 'YouTube', type: 'free' },
      { name: 'Digital Forensics Course', url: 'https://udemy.com', platform: 'Udemy', type: 'paid' },
    ],
  },
  {
    id: 'security-consultant',
    name: 'Security Consultant',
    icon: '🛡️',
    sectorId: 'cybersecurity',
    description: 'Advise on security strategy',
    detailedDescription: 'Security Consultants assess organizational security and recommend improvements. They conduct audits, develop policies, and guide security implementations.',
    salary: { min: 85000, max: 160000, currency: 'USD' },
    skills: ['Risk Assessment', 'Security Auditing', 'Compliance', 'Policy Development', 'Communication'],
    difficulty: 'advanced',
    roadmap: [
      { step: 1, title: 'Security Fundamentals', description: 'Broad security knowledge' },
      { step: 2, title: 'Risk Management', description: 'Risk assessment methods' },
      { step: 3, title: 'Compliance', description: 'ISO 27001, NIST' },
      { step: 4, title: 'Consulting Skills', description: 'Client management' },
    ],
    certificates: [
      { name: 'CISSP (Certified Information Systems Security Professional)', type: 'required' },
      { name: 'CISM (Certified Information Security Manager)', type: 'optional' },
    ],
    links: [
      { name: 'Security Consulting Guide', url: 'https://youtube.com', platform: 'YouTube', type: 'free' },
      { name: 'Security Consultant Training', url: 'https://udemy.com', platform: 'Udemy', type: 'paid' },
    ],
  },

  // Mechanical Engineering (4 jobs)
  {
    id: 'mechanical-design-engineer',
    name: 'Mechanical Design Engineer',
    icon: '📐',
    sectorId: 'mechanical',
    description: 'Design mechanical systems',
    detailedDescription: 'Mechanical Design Engineers create blueprints and models for mechanical devices. They use CAD software to design everything from small components to large machinery.',
    salary: { min: 60000, max: 130000, currency: 'USD' },
    skills: ['CAD', 'SolidWorks', 'AutoCAD', 'Material Science', 'Manufacturing', 'Analysis'],
    difficulty: 'intermediate',
    roadmap: [
      { step: 1, title: 'Engineering Basics', description: 'Mechanics and materials' },
      { step: 2, title: 'CAD Software', description: 'Learn SolidWorks/AutoCAD' },
      { step: 3, title: 'Design Principles', description: 'Design for manufacturing' },
      { step: 4, title: 'Simulation', description: 'FEA and CFD basics' },
    ],
    certificates: [
      { name: 'Certified SolidWorks Professional (CSWP)', type: 'optional' },
      { name: 'AutoCAD Certified Professional', type: 'optional' },
    ],
    links: [
      { name: 'CAD Design Tutorial', url: 'https://youtube.com', platform: 'YouTube', type: 'free' },
      { name: 'Mechanical Design Masterclass', url: 'https://udemy.com', platform: 'Udemy', type: 'paid' },
    ],
  },
  {
    id: 'robotics-engineer',
    name: 'Robotics Engineer',
    icon: '🤖',
    sectorId: 'mechanical',
    description: 'Build intelligent robots',
    detailedDescription: 'Robotics Engineers design and develop robots for various applications. They integrate mechanical design, electronics, and programming to create automated systems.',
    salary: { min: 70000, max: 150000, currency: 'USD' },
    skills: ['Robotics', 'Control Systems', 'Python', 'ROS', 'Embedded Systems', 'AI'],
    difficulty: 'advanced',
    roadmap: [
      { step: 1, title: 'Mechanical & Electronics', description: 'Fundamentals' },
      { step: 2, title: 'Programming', description: 'Python and C++' },
      { step: 3, title: 'ROS (Robot Operating System)', description: 'Robot framework' },
      { step: 4, title: 'Computer Vision', description: 'Sensors and perception' },
      { step: 5, title: 'AI & Control', description: 'Advanced robotics' },
    ],
    certificates: [
      { name: 'ROS Industrial Training', type: 'optional' },
    ],
    links: [
      { name: 'Robotics Basics', url: 'https://youtube.com', platform: 'YouTube', type: 'free' },
      { name: 'Robotics & AI Course', url: 'https://udemy.com', platform: 'Udemy', type: 'paid' },
    ],
  },
  {
    id: 'manufacturing-engineer',
    name: 'Manufacturing Engineer',
    icon: '🏭',
    sectorId: 'mechanical',
    description: 'Optimize production processes',
    detailedDescription: 'Manufacturing Engineers design and improve manufacturing systems. They focus on efficiency, quality, and cost-effectiveness in production.',
    salary: { min: 55000, max: 115000, currency: 'USD' },
    skills: ['Lean Manufacturing', 'Six Sigma', 'Process Optimization', 'Quality Control', 'CAD'],
    difficulty: 'intermediate',
    roadmap: [
      { step: 1, title: 'Engineering Basics', description: 'Manufacturing processes' },
      { step: 2, title: 'Quality Management', description: 'Six Sigma methodology' },
      { step: 3, title: 'Process Improvement', description: 'Lean principles' },
      { step: 4, title: 'Automation', description: 'Manufacturing automation' },
    ],
    certificates: [
      { name: 'Six Sigma Green Belt', type: 'optional' },
      { name: 'Lean Manufacturing Certification', type: 'optional' },
    ],
    links: [
      { name: 'Manufacturing Engineering', url: 'https://youtube.com', platform: 'YouTube', type: 'free' },
      { name: 'Lean Six Sigma Course', url: 'https://coursera.org', platform: 'Coursera', type: 'paid' },
    ],
  },
  {
    id: 'hvac-engineer',
    name: 'HVAC Engineer',
    icon: '❄️',
    sectorId: 'mechanical',
    description: 'Design climate control systems',
    detailedDescription: 'HVAC Engineers design heating, ventilation, and air conditioning systems for buildings. They ensure comfortable and energy-efficient indoor environments.',
    salary: { min: 55000, max: 110000, currency: 'USD' },
    skills: ['HVAC Design', 'Thermodynamics', 'Energy Efficiency', 'Building Codes', 'AutoCAD'],
    difficulty: 'intermediate',
    roadmap: [
      { step: 1, title: 'Thermodynamics', description: 'Heat transfer basics' },
      { step: 2, title: 'HVAC Systems', description: 'System components' },
      { step: 3, title: 'Design Software', description: 'HVAC design tools' },
      { step: 4, title: 'Energy Codes', description: 'Building standards' },
    ],
    certificates: [
      { name: 'HVAC Excellence Certification', type: 'optional' },
      { name: 'LEED Green Associate', type: 'optional' },
    ],
    links: [
      { name: 'HVAC Fundamentals', url: 'https://youtube.com', platform: 'YouTube', type: 'free' },
      { name: 'HVAC Design Course', url: 'https://udemy.com', platform: 'Udemy', type: 'paid' },
    ],
  },

  // Electronics (4 jobs)
  {
    id: 'embedded-systems-engineer',
    name: 'Embedded Systems Engineer',
    icon: '💾',
    sectorId: 'electronics',
    description: 'Program hardware devices',
    detailedDescription: 'Embedded Systems Engineers design and program computer systems embedded in devices. They work on IoT, automotive, and consumer electronics.',
    salary: { min: 65000, max: 135000, currency: 'USD' },
    skills: ['C/C++', 'Microcontrollers', 'RTOS', 'Hardware Design', 'Debugging', 'IoT'],
    difficulty: 'advanced',
    roadmap: [
      { step: 1, title: 'Electronics Basics', description: 'Circuits and components' },
      { step: 2, title: 'C Programming', description: 'Low-level programming' },
      { step: 3, title: 'Microcontrollers', description: 'Arduino, STM32' },
      { step: 4, title: 'RTOS', description: 'Real-time operating systems' },
    ],
    certificates: [
      { name: 'ARM Accredited Engineer', type: 'optional' },
    ],
    links: [
      { name: 'Embedded Systems Tutorial', url: 'https://youtube.com', platform: 'YouTube', type: 'free' },
      { name: 'Embedded Systems Masterclass', url: 'https://udemy.com', platform: 'Udemy', type: 'paid' },
    ],
  },
  {
    id: 'vlsi-engineer',
    name: 'VLSI Design Engineer',
    icon: '🔬',
    sectorId: 'electronics',
    description: 'Design integrated circuits',
    detailedDescription: 'VLSI Engineers design Very Large Scale Integrated circuits. They create chips used in computers, smartphones, and electronic devices.',
    salary: { min: 70000, max: 145000, currency: 'USD' },
    skills: ['Verilog', 'VHDL', 'Circuit Design', 'ASIC', 'FPGA', 'Digital Logic'],
    difficulty: 'advanced',
    roadmap: [
      { step: 1, title: 'Digital Electronics', description: 'Logic gates and circuits' },
      { step: 2, title: 'HDL', description: 'Learn Verilog or VHDL' },
      { step: 3, title: 'FPGA', description: 'FPGA programming' },
      { step: 4, title: 'ASIC Design', description: 'Chip design flow' },
    ],
    certificates: [
      { name: 'Cadence Certified Professional', type: 'optional' },
    ],
    links: [
      { name: 'VLSI Design Basics', url: 'https://youtube.com', platform: 'YouTube', type: 'free' },
      { name: 'VLSI Complete Course', url: 'https://udemy.com', platform: 'Udemy', type: 'paid' },
    ],
  },
  {
    id: 'pcb-designer',
    name: 'PCB Designer',
    icon: '🔧',
    sectorId: 'electronics',
    description: 'Design printed circuit boards',
    detailedDescription: 'PCB Designers create layouts for printed circuit boards. They ensure proper component placement, routing, and manufacturing feasibility.',
    salary: { min: 50000, max: 100000, currency: 'USD' },
    skills: ['PCB Design', 'Altium', 'Eagle', 'KiCad', 'Signal Integrity', 'Manufacturing'],
    difficulty: 'intermediate',
    roadmap: [
      { step: 1, title: 'Electronics Basics', description: 'Components and circuits' },
      { step: 2, title: 'PCB Software', description: 'Altium or KiCad' },
      { step: 3, title: 'Design Rules', description: 'PCB design guidelines' },
      { step: 4, title: 'Manufacturing', description: 'Fabrication process' },
    ],
    certificates: [
      { name: 'IPC Designer Certification', type: 'optional' },
    ],
    links: [
      { name: 'PCB Design Tutorial', url: 'https://youtube.com', platform: 'YouTube', type: 'free' },
      { name: 'Professional PCB Design', url: 'https://udemy.com', platform: 'Udemy', type: 'paid' },
    ],
  },
  {
    id: 'iot-developer',
    name: 'IoT Developer',
    icon: '📡',
    sectorId: 'electronics',
    description: 'Build Internet of Things devices',
    detailedDescription: 'IoT Developers create connected devices that communicate over the internet. They integrate hardware, software, and cloud services.',
    salary: { min: 60000, max: 130000, currency: 'USD' },
    skills: ['IoT Protocols', 'Embedded Programming', 'Cloud Platforms', 'Sensors', 'Networking'],
    difficulty: 'intermediate',
    roadmap: [
      { step: 1, title: 'Electronics & Programming', description: 'Basics' },
      { step: 2, title: 'IoT Platforms', description: 'Arduino, Raspberry Pi' },
      { step: 3, title: 'Communication', description: 'MQTT, HTTP, BLE' },
      { step: 4, title: 'Cloud Integration', description: 'AWS IoT, Azure IoT' },
    ],
    certificates: [
      { name: 'AWS IoT Specialty', type: 'optional' },
    ],
    links: [
      { name: 'IoT Projects', url: 'https://youtube.com', platform: 'YouTube', type: 'free' },
      { name: 'Complete IoT Course', url: 'https://udemy.com', platform: 'Udemy', type: 'paid' },
    ],
  },

  // Civil Engineering (3 jobs)
  {
    id: 'structural-engineer',
    name: 'Structural Engineer',
    icon: '🏛️',
    sectorId: 'civil',
    description: 'Design building structures',
    detailedDescription: 'Structural Engineers design the framework of buildings and infrastructure. They ensure structures can withstand loads and environmental conditions.',
    salary: { min: 60000, max: 125000, currency: 'USD' },
    skills: ['Structural Analysis', 'CAD', 'Building Codes', 'Concrete Design', 'Steel Design'],
    difficulty: 'advanced',
    roadmap: [
      { step: 1, title: 'Engineering Fundamentals', description: 'Statics and mechanics' },
      { step: 2, title: 'Structural Analysis', description: 'Load analysis' },
      { step: 3, title: 'Design Software', description: 'ETABS, SAP2000' },
      { step: 4, title: 'Codes & Standards', description: 'Building regulations' },
    ],
    certificates: [
      { name: 'Professional Engineer (PE)', type: 'required' },
      { name: 'Structural Engineering Certification', type: 'optional' },
    ],
    links: [
      { name: 'Structural Engineering Basics', url: 'https://youtube.com', platform: 'YouTube', type: 'free' },
      { name: 'Structural Design Course', url: 'https://coursera.org', platform: 'Coursera', type: 'paid' },
    ],
  },
  {
    id: 'transportation-engineer',
    name: 'Transportation Engineer',
    icon: '🚗',
    sectorId: 'civil',
    description: 'Design transportation systems',
    detailedDescription: 'Transportation Engineers plan and design roads, highways, and transit systems. They focus on traffic flow, safety, and efficiency.',
    salary: { min: 55000, max: 115000, currency: 'USD' },
    skills: ['Traffic Engineering', 'Highway Design', 'Transportation Planning', 'GIS', 'Simulation'],
    difficulty: 'intermediate',
    roadmap: [
      { step: 1, title: 'Civil Engineering Basics', description: 'Fundamentals' },
      { step: 2, title: 'Transportation Planning', description: 'System design' },
      { step: 3, title: 'Traffic Analysis', description: 'Flow modeling' },
      { step: 4, title: 'Design Software', description: 'Highway design tools' },
    ],
    certificates: [
      { name: 'Professional Traffic Operations Engineer (PTOE)', type: 'optional' },
    ],
    links: [
      { name: 'Transportation Engineering', url: 'https://youtube.com', platform: 'YouTube', type: 'free' },
      { name: 'Highway Design Course', url: 'https://udemy.com', platform: 'Udemy', type: 'paid' },
    ],
  },
  {
    id: 'environmental-engineer',
    name: 'Environmental Engineer',
    icon: '🌱',
    sectorId: 'civil',
    description: 'Protect the environment',
    detailedDescription: 'Environmental Engineers develop solutions to environmental problems. They work on water treatment, waste management, and pollution control.',
    salary: { min: 55000, max: 110000, currency: 'USD' },
    skills: ['Environmental Science', 'Water Treatment', 'Waste Management', 'Sustainability', 'Regulations'],
    difficulty: 'intermediate',
    roadmap: [
      { step: 1, title: 'Environmental Science', description: 'Ecology basics' },
      { step: 2, title: 'Engineering Principles', description: 'Civil engineering' },
      { step: 3, title: 'Treatment Systems', description: 'Water and waste' },
      { step: 4, title: 'Regulations', description: 'Environmental laws' },
    ],
    certificates: [
      { name: 'Professional Engineer (PE) Environmental', type: 'optional' },
    ],
    links: [
      { name: 'Environmental Engineering', url: 'https://youtube.com', platform: 'YouTube', type: 'free' },
      { name: 'Environmental Solutions', url: 'https://coursera.org', platform: 'Coursera', type: 'paid' },
    ],
  },

  // Medical (5 jobs)
  {
    id: 'medical-doctor',
    name: 'Medical Doctor',
    icon: '👨‍⚕️',
    sectorId: 'medical',
    description: 'Diagnose and treat patients',
    detailedDescription: 'Medical Doctors diagnose illnesses, prescribe treatments, and provide comprehensive healthcare. They can specialize in various fields of medicine.',
    salary: { min: 150000, max: 350000, currency: 'USD' },
    skills: ['Medical Knowledge', 'Diagnosis', 'Patient Care', 'Communication', 'Empathy'],
    difficulty: 'advanced',
    roadmap: [
      { step: 1, title: 'Pre-Med Education', description: 'Bachelor\'s degree' },
      { step: 2, title: 'Medical School', description: '4 years MD degree' },
      { step: 3, title: 'Residency', description: '3-7 years training' },
      { step: 4, title: 'Board Certification', description: 'Specialty certification' },
    ],
    certificates: [
      { name: 'Medical License', type: 'required' },
      { name: 'Board Certification', type: 'required' },
    ],
    links: [
      { name: 'Medical Education Guide', url: 'https://youtube.com', platform: 'YouTube', type: 'free' },
      { name: 'USMLE Prep Course', url: 'https://udemy.com', platform: 'Udemy', type: 'paid' },
    ],
  },
  {
    id: 'nurse-practitioner',
    name: 'Nurse Practitioner',
    icon: '👩‍⚕️',
    sectorId: 'medical',
    description: 'Provide advanced nursing care',
    detailedDescription: 'Nurse Practitioners provide primary and specialty healthcare services. They can diagnose conditions, prescribe medications, and manage patient care.',
    salary: { min: 90000, max: 150000, currency: 'USD' },
    skills: ['Clinical Skills', 'Patient Assessment', 'Prescribing', 'Health Management', 'Communication'],
    difficulty: 'advanced',
    roadmap: [
      { step: 1, title: 'Nursing Degree', description: 'BSN required' },
      { step: 2, title: 'RN Experience', description: '1-2 years nursing' },
      { step: 3, title: 'Master\'s Degree', description: 'MSN or DNP' },
      { step: 4, title: 'Certification', description: 'NP certification' },
    ],
    certificates: [
      { name: 'Nurse Practitioner Certification', type: 'required' },
    ],
    links: [
      { name: 'NP Career Guide', url: 'https://youtube.com', platform: 'YouTube', type: 'free' },
      { name: 'NP Certification Prep', url: 'https://udemy.com', platform: 'Udemy', type: 'paid' },
    ],
  },
  {
    id: 'medical-researcher',
    name: 'Medical Researcher',
    icon: '🔬',
    sectorId: 'medical',
    description: 'Discover medical breakthroughs',
    detailedDescription: 'Medical Researchers conduct studies to understand diseases and develop new treatments. They work in labs, universities, and pharmaceutical companies.',
    salary: { min: 70000, max: 150000, currency: 'USD' },
    skills: ['Research Methods', 'Data Analysis', 'Laboratory Techniques', 'Scientific Writing', 'Critical Thinking'],
    difficulty: 'advanced',
    roadmap: [
      { step: 1, title: 'Science Degree', description: 'Biology or related field' },
      { step: 2, title: 'Graduate Study', description: 'Master\'s or PhD' },
      { step: 3, title: 'Lab Experience', description: 'Research projects' },
      { step: 4, title: 'Specialization', description: 'Focus area' },
    ],
    certificates: [
      { name: 'Good Clinical Practice (GCP)', type: 'optional' },
    ],
    links: [
      { name: 'Medical Research Methods', url: 'https://youtube.com', platform: 'YouTube', type: 'free' },
      { name: 'Clinical Research Course', url: 'https://coursera.org', platform: 'Coursera', type: 'paid' },
    ],
  },
  {
    id: 'radiologist',
    name: 'Radiologist',
    icon: '🩻',
    sectorId: 'medical',
    description: 'Interpret medical images',
    detailedDescription: 'Radiologists use imaging technology to diagnose diseases. They interpret X-rays, CT scans, MRIs, and ultrasounds.',
    salary: { min: 200000, max: 450000, currency: 'USD' },
    skills: ['Medical Imaging', 'Anatomy', 'Diagnosis', 'Technology', 'Attention to Detail'],
    difficulty: 'advanced',
    roadmap: [
      { step: 1, title: 'Medical School', description: 'MD degree' },
      { step: 2, title: 'Radiology Residency', description: '4-5 years' },
      { step: 3, title: 'Fellowship', description: 'Optional subspecialty' },
      { step: 4, title: 'Board Certification', description: 'Radiology boards' },
    ],
    certificates: [
      { name: 'Board Certification in Radiology', type: 'required' },
    ],
    links: [
      { name: 'Radiology Basics', url: 'https://youtube.com', platform: 'YouTube', type: 'free' },
      { name: 'Radiology Board Prep', url: 'https://udemy.com', platform: 'Udemy', type: 'paid' },
    ],
  },
  {
    id: 'pharmacist',
    name: 'Pharmacist',
    icon: '💊',
    sectorId: 'medical',
    description: 'Dispense medications',
    detailedDescription: 'Pharmacists dispense medications and advise patients on proper usage. They ensure safe and effective drug therapy.',
    salary: { min: 100000, max: 160000, currency: 'USD' },
    skills: ['Pharmacology', 'Patient Counseling', 'Drug Interactions', 'Healthcare', 'Accuracy'],
    difficulty: 'advanced',
    roadmap: [
      { step: 1, title: 'Pharmacy Prerequisites', description: 'Science courses' },
      { step: 2, title: 'Pharmacy School', description: 'PharmD degree' },
      { step: 3, title: 'Licensure', description: 'NAPLEX exam' },
      { step: 4, title: 'Specialization', description: 'Optional residency' },
    ],
    certificates: [
      { name: 'Pharmacy License', type: 'required' },
    ],
    links: [
      { name: 'Pharmacy Career Guide', url: 'https://youtube.com', platform: 'YouTube', type: 'free' },
      { name: 'NAPLEX Prep Course', url: 'https://udemy.com', platform: 'Udemy', type: 'paid' },
    ],
  },

  // Design & UX (5 jobs)
  {
    id: 'ux-designer',
    name: 'UX Designer',
    icon: '🎨',
    sectorId: 'design-ux',
    description: 'Design user experiences',
    detailedDescription: 'UX Designers create intuitive and enjoyable user experiences. They research user needs, design interfaces, and test usability.',
    salary: { min: 60000, max: 140000, currency: 'USD' },
    skills: ['User Research', 'Wireframing', 'Prototyping', 'Figma', 'User Testing', 'Empathy'],
    difficulty: 'intermediate',
    roadmap: [
      { step: 1, title: 'Design Basics', description: 'UI/UX fundamentals' },
      { step: 2, title: 'Design Tools', description: 'Figma, Adobe XD' },
      { step: 3, title: 'User Research', description: 'Research methods' },
      { step: 4, title: 'Portfolio', description: 'Build case studies' },
    ],
    certificates: [
      { name: 'Google UX Design Certificate', type: 'optional' },
      { name: 'Nielsen Norman Group UX Certification', type: 'optional' },
    ],
    links: [
      { name: 'UX Design Basics', url: 'https://youtube.com', platform: 'YouTube', type: 'free' },
      { name: 'Complete UX Design Course', url: 'https://udemy.com', platform: 'Udemy', type: 'paid' },
    ],
  },
  {
    id: 'ui-designer',
    name: 'UI Designer',
    icon: '🖼️',
    sectorId: 'design-ux',
    description: 'Design visual interfaces',
    detailedDescription: 'UI Designers create beautiful and functional interfaces. They focus on visual design, typography, color, and layout.',
    salary: { min: 55000, max: 130000, currency: 'USD' },
    skills: ['Visual Design', 'Typography', 'Color Theory', 'Figma', 'Design Systems', 'Illustration'],
    difficulty: 'intermediate',
    roadmap: [
      { step: 1, title: 'Design Fundamentals', description: 'Visual principles' },
      { step: 2, title: 'Design Tools', description: 'Figma, Sketch' },
      { step: 3, title: 'Design Systems', description: 'Component libraries' },
      { step: 4, title: 'Portfolio', description: 'Showcase work' },
    ],
    certificates: [
      { name: 'Adobe Certified Professional', type: 'optional' },
    ],
    links: [
      { name: 'UI Design Tutorial', url: 'https://youtube.com', platform: 'YouTube', type: 'free' },
      { name: 'UI Design Masterclass', url: 'https://udemy.com', platform: 'Udemy', type: 'paid' },
    ],
  },
  {
    id: 'graphic-designer',
    name: 'Graphic Designer',
    icon: '✏️',
    sectorId: 'design-ux',
    description: 'Create visual content',
    detailedDescription: 'Graphic Designers create visual content for print and digital media. They design logos, brochures, posters, and marketing materials.',
    salary: { min: 45000, max: 100000, currency: 'USD' },
    skills: ['Adobe Creative Suite', 'Typography', 'Branding', 'Layout Design', 'Illustration'],
    difficulty: 'beginner',
    roadmap: [
      { step: 1, title: 'Design Basics', description: 'Visual principles' },
      { step: 2, title: 'Adobe Tools', description: 'Photoshop, Illustrator' },
      { step: 3, title: 'Branding', description: 'Logo and identity' },
      { step: 4, title: 'Portfolio', description: 'Build diverse work' },
    ],
    certificates: [
      { name: 'Adobe Certified Professional', type: 'optional' },
    ],
    links: [
      { name: 'Graphic Design Basics', url: 'https://youtube.com', platform: 'YouTube', type: 'free' },
      { name: 'Graphic Design Bootcamp', url: 'https://udemy.com', platform: 'Udemy', type: 'paid' },
    ],
  },
  {
    id: 'motion-designer',
    name: 'Motion Designer',
    icon: '🎬',
    sectorId: 'design-ux',
    description: 'Animate graphics and videos',
    detailedDescription: 'Motion Designers create animated graphics and videos. They bring static designs to life through animation and visual effects.',
    salary: { min: 50000, max: 120000, currency: 'USD' },
    skills: ['After Effects', 'Animation', 'Video Editing', 'Motion Graphics', '3D Animation'],
    difficulty: 'intermediate',
    roadmap: [
      { step: 1, title: 'Design Fundamentals', description: 'Visual basics' },
      { step: 2, title: 'After Effects', description: 'Animation software' },
      { step: 3, title: 'Animation Principles', description: 'Timing and motion' },
      { step: 4, title: 'Portfolio', description: 'Demo reel' },
    ],
    certificates: [
      { name: 'Adobe Certified Professional - After Effects', type: 'optional' },
    ],
    links: [
      { name: 'Motion Graphics Tutorial', url: 'https://youtube.com', platform: 'YouTube', type: 'free' },
      { name: 'Motion Design Course', url: 'https://udemy.com', platform: 'Udemy', type: 'paid' },
    ],
  },
  {
    id: 'product-designer',
    name: 'Product Designer',
    icon: '📱',
    sectorId: 'design-ux',
    description: 'Design digital products',
    detailedDescription: 'Product Designers own the entire design process from research to visual design. They combine UX and UI skills to create complete product experiences.',
    salary: { min: 70000, max: 160000, currency: 'USD' },
    skills: ['UX Design', 'UI Design', 'Product Thinking', 'Prototyping', 'User Research', 'Figma'],
    difficulty: 'advanced',
    roadmap: [
      { step: 1, title: 'UX & UI Basics', description: 'Combined skills' },
      { step: 2, title: 'Product Thinking', description: 'Business + design' },
      { step: 3, title: 'Advanced Prototyping', description: 'Interactive designs' },
      { step: 4, title: 'Portfolio', description: 'End-to-end projects' },
    ],
    certificates: [
      { name: 'Interaction Design Foundation', type: 'optional' },
    ],
    links: [
      { name: 'Product Design Guide', url: 'https://youtube.com', platform: 'YouTube', type: 'free' },
      { name: 'Product Design Masterclass', url: 'https://udemy.com', platform: 'Udemy', type: 'paid' },
    ],
  },

  // Management (3 jobs)
  {
    id: 'project-manager',
    name: 'Project Manager',
    icon: '📋',
    sectorId: 'management',
    description: 'Lead and deliver projects',
    detailedDescription: 'Project Managers plan, execute, and close projects. They coordinate teams, manage resources, and ensure projects meet objectives on time and within budget.',
    salary: { min: 65000, max: 140000, currency: 'USD' },
    skills: ['Project Management', 'Leadership', 'Communication', 'Risk Management', 'Agile'],
    difficulty: 'intermediate',
    roadmap: [
      { step: 1, title: 'PM Fundamentals', description: 'Project basics' },
      { step: 2, title: 'Methodologies', description: 'Agile, Waterfall, Scrum' },
      { step: 3, title: 'Tools', description: 'Jira, Asana, MS Project' },
      { step: 4, title: 'Certification', description: 'PMP or similar' },
    ],
    certificates: [
      { name: 'Project Management Professional (PMP)', type: 'optional' },
      { name: 'Certified Scrum Master (CSM)', type: 'optional' },
    ],
    links: [
      { name: 'Project Management Basics', url: 'https://youtube.com', platform: 'YouTube', type: 'free' },
      { name: 'PMP Exam Prep', url: 'https://udemy.com', platform: 'Udemy', type: 'paid' },
    ],
  },
  {
    id: 'product-manager',
    name: 'Product Manager',
    icon: '🚀',
    sectorId: 'management',
    description: 'Define product strategy',
    detailedDescription: 'Product Managers define product vision and strategy. They work with cross-functional teams to build products users love.',
    salary: { min: 80000, max: 180000, currency: 'USD' },
    skills: ['Product Strategy', 'User Research', 'Data Analysis', 'Communication', 'Prioritization'],
    difficulty: 'advanced',
    roadmap: [
      { step: 1, title: 'Product Basics', description: 'Product lifecycle' },
      { step: 2, title: 'User Research', description: 'Customer discovery' },
      { step: 3, title: 'Data & Metrics', description: 'Analytics and KPIs' },
      { step: 4, title: 'Strategy', description: 'Product roadmapping' },
    ],
    certificates: [
      { name: 'Certified Product Manager', type: 'optional' },
    ],
    links: [
      { name: 'Product Management 101', url: 'https://youtube.com', platform: 'YouTube', type: 'free' },
      { name: 'Product Management Course', url: 'https://coursera.org', platform: 'Coursera', type: 'paid' },
    ],
  },
  {
    id: 'business-analyst',
    name: 'Business Analyst',
    icon: '📈',
    sectorId: 'management',
    description: 'Analyze business needs',
    detailedDescription: 'Business Analysts bridge business and IT. They gather requirements, analyze processes, and recommend solutions to improve efficiency.',
    salary: { min: 60000, max: 130000, currency: 'USD' },
    skills: ['Requirements Analysis', 'Process Modeling', 'SQL', 'Data Analysis', 'Communication'],
    difficulty: 'intermediate',
    roadmap: [
      { step: 1, title: 'Business Basics', description: 'Business fundamentals' },
      { step: 2, title: 'Analysis Techniques', description: 'Requirements gathering' },
      { step: 3, title: 'Tools', description: 'Excel, SQL, Tableau' },
      { step: 4, title: 'Certification', description: 'CBAP or similar' },
    ],
    certificates: [
      { name: 'Certified Business Analysis Professional (CBAP)', type: 'optional' },
    ],
    links: [
      { name: 'Business Analysis Guide', url: 'https://youtube.com', platform: 'YouTube', type: 'free' },
      { name: 'Business Analyst Course', url: 'https://udemy.com', platform: 'Udemy', type: 'paid' },
    ],
  },

  // Finance (3 jobs)
  {
    id: 'financial-analyst',
    name: 'Financial Analyst',
    icon: '💹',
    sectorId: 'finance',
    description: 'Analyze financial data',
    detailedDescription: 'Financial Analysts evaluate financial data to help businesses make informed decisions. They analyze trends, create reports, and forecast performance.',
    salary: { min: 60000, max: 130000, currency: 'USD' },
    skills: ['Financial Modeling', 'Excel', 'Accounting', 'Data Analysis', 'Forecasting'],
    difficulty: 'intermediate',
    roadmap: [
      { step: 1, title: 'Finance Basics', description: 'Accounting fundamentals' },
      { step: 2, title: 'Excel Skills', description: 'Advanced Excel' },
      { step: 3, title: 'Financial Modeling', description: 'Valuation and forecasting' },
      { step: 4, title: 'Certification', description: 'CFA or CPA' },
    ],
    certificates: [
      { name: 'Chartered Financial Analyst (CFA)', type: 'optional' },
      { name: 'Certified Public Accountant (CPA)', type: 'optional' },
    ],
    links: [
      { name: 'Financial Analysis Basics', url: 'https://youtube.com', platform: 'YouTube', type: 'free' },
      { name: 'Financial Modeling Course', url: 'https://udemy.com', platform: 'Udemy', type: 'paid' },
    ],
  },
  {
    id: 'investment-banker',
    name: 'Investment Banker',
    icon: '🏦',
    sectorId: 'finance',
    description: 'Facilitate financial deals',
    detailedDescription: 'Investment Bankers help companies raise capital through debt and equity offerings. They advise on mergers, acquisitions, and financial strategy.',
    salary: { min: 100000, max: 300000, currency: 'USD' },
    skills: ['Financial Modeling', 'Valuation', 'M&A', 'Presentation', 'Networking'],
    difficulty: 'advanced',
    roadmap: [
      { step: 1, title: 'Finance Degree', description: 'Strong academics' },
      { step: 2, title: 'Internships', description: 'Banking internships' },
      { step: 3, title: 'Analyst Role', description: '2-3 years experience' },
      { step: 4, title: 'Associate', description: 'MBA or promotion' },
    ],
    certificates: [
      { name: 'CFA (Chartered Financial Analyst)', type: 'optional' },
    ],
    links: [
      { name: 'Investment Banking 101', url: 'https://youtube.com', platform: 'YouTube', type: 'free' },
      { name: 'IB Technical Skills', url: 'https://udemy.com', platform: 'Udemy', type: 'paid' },
    ],
  },
  {
    id: 'accountant',
    name: 'Accountant',
    icon: '🧮',
    sectorId: 'finance',
    description: 'Manage financial records',
    detailedDescription: 'Accountants prepare and examine financial records. They ensure accuracy, compliance with regulations, and handle taxes and audits.',
    salary: { min: 50000, max: 110000, currency: 'USD' },
    skills: ['Accounting', 'Tax Preparation', 'Auditing', 'Financial Reporting', 'Compliance'],
    difficulty: 'intermediate',
    roadmap: [
      { step: 1, title: 'Accounting Degree', description: 'Bachelor\'s in accounting' },
      { step: 2, title: 'Internship', description: 'Gain experience' },
      { step: 3, title: 'CPA Exam', description: 'Pass CPA certification' },
      { step: 4, title: 'Specialization', description: 'Tax, audit, or management' },
    ],
    certificates: [
      { name: 'Certified Public Accountant (CPA)', type: 'required' },
    ],
    links: [
      { name: 'Accounting Basics', url: 'https://youtube.com', platform: 'YouTube', type: 'free' },
      { name: 'CPA Exam Prep', url: 'https://udemy.com', platform: 'Udemy', type: 'paid' },
    ],
  },
];
